# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c889e631473f9a475c9994c8f407cdd332d92c88350f69e2c7ec10944bb4181fbbedf129ba30465e25175081b05eb6a4dfd9f4e48aae18866590fddbc3e1c3

test:
  secret_key_base: 0fd00b2bb8e0b83a1942b019f17d5278d192a461f45f23e5d1efeccbcb5586082a11d6626d2e0639e2543917592a66dedd7e8cbe75301beda22d7947461f9047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
